name: Biome CI

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "**/*.ts"
  pull_request:
    branches:
      - "master"
    paths:
      - "**/*.ts"

jobs:
  quality:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: biomejs/setup-biome@8a59bf8c5e13140007bae2680f59a2642f762001 # v2.7.1
        with:
          version: "2.4.10"

      - run: biome ci .
