name: Biome CI

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "**/*.ts"
  pull_request:
    branches:
      - "master"
    paths:
      - "**/*.ts"

jobs:
  quality:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: biomejs/setup-biome@da27d18dce2352c716f25fed9c16cde28af1c47e # v2.7.1
        with:
          version: "2.5.0"

      - run: biome ci .
