name: Biome CI

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "**/*.ts"
  pull_request:
    branches:
      - "master"
    paths:
      - "**/*.ts"

jobs:
  quality:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: biomejs/setup-biome@da79ef32b786875c075fd0abcfdd173640b96499 # v2.7.1
        with:
          version: "2.5.2"

      - run: biome ci .
